### PR TITLE
fix spec tests

### PR DESCRIPTION
**Pull request by tuxmea**
- add missing rspec-json-expectation gem
- a class declaration can be a CLASSREF or TYPE

Fixes build issues in #6 
@rnelson0 @juniorsysadmin please check for this build and rebase in case of no errors.

### CODE REVIEW

**Comment by rnelson0** [comment]
I'm gonna merge this so CI works properly, but can we get a new spec test for TYPEs soon?

**Comment by tuxmea** [comment]
Spec tests for types are already there:
```
      class{ base::demo: }
      Class['demo'] -> Class['foo']
```

**Comment by rnelson0** [comment]
TYPE is defined as https://github.com/rodjek/puppet-lint/blob/master/lib/puppet-lint/lexer.rb#L93

I believe that would not be relevant for the plugin and should probably be removed. Am I missing how it would be valid?

**Comment by tuxmea** [comment]
TYPE is also Resource.
Spec tests will fail if we omit the TYPE when having declaration like this:
```
class { 'foo': }
Class['foo'] -> Class['bar']
```

**Pull request merged**
